version: '3'
services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    network_mode: "host"

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamo-db
    network_mode: "host"

  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: oauth
      MYSQL_ROOT_PASSWORD: 'root'
    network_mode: "host"

  eureka-server:
    image: vodafone/training-eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    environment:
      server.port: 8761
    network_mode: host

  oauth-server:
    image: vodafone/training-oauth-server:0.0.1-SNAPSHOT
    environment:
      server.port: 8000
      spring.datasource.url: jdbc:mysql://localhost:3306/oauth
      redirect-uri: http://127.0.0.1:8080/login/oauth2/code/vodafone-ecommerce-client
      issuer.url: http://oauth-server:8000
    ports:
      - "8000:8000"
    network_mode: "host"
    depends_on:
      - mysql-db
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  api-gateway:
    image: vodafone/training-api-gateway:0.0.1-SNAPSHOT
    environment:
      server.port: 8080
      spring.security.oauth2.client.provider.spring.issuer-uri: http://oauth-server:8000
      eureka.client.serviceUrl.defaultZone=http: http://localhost:8761/eureka/
      spring.security.oauth2.client.registration.vodafone-ecommerce-client.redirect-uri: http://oauth-server:8080/login/oauth2/code/vodafone-ecommerce-client
    ports:
      - "8080:8080"
    network_mode: "host"
    depends_on:
      - oauth-server
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  vodafone_network:
    driver: bridge
